config/routes.rb
Janni::Application.routes.draw do

	resources :boards

  get "users/show"

  resources :pins

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  match 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'

  root :to => 'pins#index'

  devise_scope :user do
	  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url, :pinname

	#Validating Pin Name
	validates :pinname, presence: true, length: { :minimum => 5, :maximum => 35}

  #Pin Description Validation
	validates :description, presence: true, length: { :minimum => 5}

  #Checks if user_id is present for uploading a a pin
  validates :user_id, presence: true

  validates :category, presence: true

  #Pins belongs to ONE user
	belongs_to :user

	#Pin belongs to ONE Board
	belongs_to :board

  #Pin belongs to ONE Category
  belongs_to :category

  #For paperclip
  has_attached_file :image, styles: { medium: "320x240>" }
  #Validates the Image Attachment
	validates_attachment :image, presence: true,
                       content_type: { content_type: [ 'image/jpeg', 'image/jpg', 'image/png', 'image/gif' ] },
                       size: { less_than: 5.megabytes }

  #For Remote URL Image Upload
  def image_remote_url=(url_value)
	  self.image = URI.parse(url_value) unless url_value.blank?
	  super
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

	before_filter :authenticate_user!, except: [:index]
  # GET /pins
  # GET /pins.json
	def index
		@pins = Pin.order("created_at desc").page(params[:page]).per_page(30)

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @pins }
			format.js
		end
	end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
		end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
	  @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
    <%= f.error_notification %>
    <%= f.full_error :image_file_size, class: "alert alert-error" %>
    <%= f.full_error :image_content_type, class: "alert alert-error" %>

    <%= f.input :image, label: "Upload an Image" %>


    <%= f.input :pinname, input_html: { rows: "1"} %>
    <%= f.input :description, as: :text, input_html: { rows: "5"} %>

    <%= f.button :submit, class: "btn btn-primary" %>


<% end %>

app/views/pins/_pin.html.erb
<div class="box thumbnail">

  <%= link_to (image_tag pin.image(:medium)), pin %>

  <!-- Mouseover Options-->
  <% if user_signed_in? %>
      <div class="options">
        <%= link_to  "#", class: "btn btn-danger btn-mini" do %>
            <i class="icon-heart icon-white"></i>
        <% end %>

      </div>
  <% end %>

  <div class="pinwrapper">

    <p class="description">
      <%= pin.pinname %>
    </p>

    <div class="pinuserarea">
        <div class="pinuser">
          <strong>
            Added by<br>
            <%= link_to pin.user.name, pin.user %>
          </strong>
        </div>
    </div>

  </div>

</div>

app/views/pins/edit.html.erb
<div class="container">
  <h1>Editing pin</h1>

  <%= render 'form' %>

  <%= link_to 'Back', @pin, class: "btn btn-mini btn-primary" %>

</div>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

    <div id="pins" >
      <%= render @pins %>
    </div>
<%= will_paginate @pins %>

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
    $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
$('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
$('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path, class: "btn btn-small btn-primary" %>

app/views/pins/show.html.erb
<div class="container-fluid">
  <div class="row-fluid">

    <!-- Pin image Span -->
    <div class="show_pin span8">

      <div>
        <%=  image_tag @pin.image %>
      </div>



      <div id="pinlightbox" class="lightbox hide fade"  tabindex="-1" role="dialog" aria-hidden="true">
        <div class='lightbox-content'>
          <%=  image_tag @pin.image %>
        </div>
      </div>

      <div class="description">

        <p>
          <%= @pin.pinname %>
        </p>

        <%= link_to  "#", class: "btn btn-danger btn-small" do %>
            <i class="icon-heart icon-white"></i> Like
        <% end %>


        <div class="pull-right">
          <%= link_to  "#pinlightbox", class: "btn btn-small", :data => {:toggle=>"lightbox"} do %>
              <i class="icon-zoom-in"></i> Toggle
          <% end %>
        </div>
      </div>
    </div>
    <!--Pin Image Span END -->


    <!-- Pin Image Info and Comments -->
    <div class="span4 ">
      <div class="show_pin_user">
        <div class="media sho_pin_user">
          <a class="pull-left" >
            <%= image_tag @pin.user.avatar.url(:thumb), class: "size48" %>
          </a>
          <div class="media-body">
            <h4 class="media-heading show_pin_user_name"><%= @pin.user.name%></h4>
            <small class="show_pin_user_meta">
              <%= link_to "View my Profile", @pin.user %>
            </small>
          </div>
          <div class="btn-group pull-right">

            <%= link_to  root_path, class: "btn btn-small" do %>
                <i class="icon-arrow-left "></i> Back
            <% end %>
            <% if current_user == @pin.user %>
                <%= link_to  edit_pin_path(@pin), class: "btn btn-small" do %>
                    <i class="icon-edit "></i> Edit
                <% end %>
                <%= link_to @pin, method: :delete, data: { confirm: 'Are you sure?' },
                            class: "btn btn-small btn-danger" do %>
                    <i class="icon-trash "></i> Delete
                <% end %>
                <% end %>
          </div>
        </div>
      </div>

      <hr>

      <p>
        <%= @pin.description %> <br>
      </p>

      <hr>

      <div>
      <!-- Share Button BEGIN -->
      <div class="addthis_toolbox addthis_default_style ">
        <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
        <a class="addthis_button_tweet"></a>
        <a class="addthis_button_pinterest_pinit"></a>
      </div>
      <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
      <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-51e7733c196e2f4b"></script>
      <!-- Share Button END -->
      </div>


<!--      &lt;!&ndash; Disqus Plugin &ndash;&gt;
      <div id="disqus_thread"></div>
      <script type="text/javascript">
          /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
          var disqus_shortname = 'amphitryon'; // required: replace example with your forum shortname

          /* * * DON'T EDIT BELOW THIS LINE * * */
          (function() {
              var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
              dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
              (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          })();
      </script>
      <noscript>Please enable JavaScript to view the Comments Area</noscript>
    </div>-->


  </div>
 </div>
</div>